version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    env_file:
      - ./env/app.env
  ml:
    build: ./ml
    ports:
      - "8000:8000"
    env_file:
      - ./env/ml.env
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trendml
    ports:
      - "5432:5432"